/** OpenSpec 核心模块统一导出入口 */

export { archiveChange } from "../sync/archive.js"
export { prepareApply } from "./workflow/apply.js"
export { bulkArchiveChanges } from "../sync/bulk-archive.js"
export { loadProjectConfig } from "./project/config.js"
export { resolveChangeMeta } from "./change/change.js"
export { continueChange } from "./workflow/continue.js"
export { updateDesign } from "./artifact/design.js"
export { fastForwardChange } from "./workflow/ff.js"
export { getArtifactStatus, getChangeStatus } from "./change/status.js"
export { getArtifactInstructions } from "./artifact/instructions.js"
export { initializeOpenSpec } from "./project/init.js"
export { listChanges } from "./change/list.js"
export { createChangeScaffold } from "./change/new.js"
export { updateProposal } from "./artifact/proposal.js"
export { proposeChange } from "./workflow/propose.js"
export { listSchemas } from "./model/schemas.js"
export { updateSpecs } from "./artifact/specs.js"
export { listTemplateInfos, resolveTemplateInfo } from "../util/templates.js"
export { updateTasks } from "./artifact/tasks.js"
export { syncChangeSpecs } from "../sync/sync.js"
export { validateChange } from "./workflow/validate.js"
export { verifyChange } from "./workflow/verify.js"
